# Form implementation generated from reading ui file 'c:\Users\HMB\OneDrive\Documents\GitHub\DatabseProjectStuff\create_Event.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(613, 626)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(220, 20, 141, 61))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 160, 81, 16))
        self.label.setObjectName("label")
        self.EventNameLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EventNameLine.setGeometry(QtCore.QRect(160, 160, 381, 22))
        self.EventNameLine.setObjectName("EventNameLine")
        self.EventDescriptionLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EventDescriptionLine.setGeometry(QtCore.QRect(160, 210, 381, 61))
        self.EventDescriptionLine.setObjectName("EventDescriptionLine")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 210, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 310, 81, 16))
        self.label_4.setObjectName("label_4")
        self.EventDateLine = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.EventDateLine.setGeometry(QtCore.QRect(160, 310, 110, 22))
        self.EventDateLine.setObjectName("EventDateLine")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 410, 121, 21))
        self.label_5.setObjectName("label_5")
        self.CreateButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.CreateButton.setGeometry(QtCore.QRect(440, 530, 93, 28))
        self.CreateButton.setObjectName("CreateButton")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 360, 91, 20))
        self.label_6.setObjectName("label_6")
        self.FundsLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.FundsLine.setGeometry(QtCore.QRect(160, 360, 381, 22))
        self.FundsLine.setObjectName("FundsLine")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 470, 131, 20))
        self.label_7.setObjectName("label_7")
        self.AdminAddLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.AdminAddLine.setGeometry(QtCore.QRect(160, 470, 381, 22))
        self.AdminAddLine.setObjectName("AdminAddLine")
        self.ClubAssociatted = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ClubAssociatted.setGeometry(QtCore.QRect(160, 410, 381, 22))
        self.ClubAssociatted.setObjectName("ClubAssociatted")
        self.EventIDLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.EventIDLine.setGeometry(QtCore.QRect(160, 120, 381, 22))
        self.EventIDLine.setText("")
        self.EventIDLine.setObjectName("EventIDLine")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(50, 120, 81, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">EVENTS</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Event Name"))
        self.label_2.setText(_translate("MainWindow", "Event Description"))
        self.label_4.setText(_translate("MainWindow", "Event Date"))
        self.label_5.setText(_translate("MainWindow", "Club Associatted(ID)"))
        self.CreateButton.setText(_translate("MainWindow", "Create"))
        self.label_6.setText(_translate("MainWindow", "Funds Required"))
        self.label_7.setText(_translate("MainWindow", "Admin Associated:(ID)"))
        self.label_3.setText(_translate("MainWindow", "Event ID"))
