USE [master]
GO
/****** Object:  Database [student club]    Script Date: 12/6/2023 11:20:02 PM ******/
CREATE DATABASE [student club]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'student club', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\student club.mdf' , SIZE = 73728KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'student club_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\student club_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [student club] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [student club].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [student club] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [student club] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [student club] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [student club] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [student club] SET ARITHABORT OFF 
GO
ALTER DATABASE [student club] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [student club] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [student club] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [student club] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [student club] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [student club] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [student club] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [student club] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [student club] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [student club] SET  DISABLE_BROKER 
GO
ALTER DATABASE [student club] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [student club] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [student club] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [student club] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [student club] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [student club] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [student club] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [student club] SET RECOVERY FULL 
GO
ALTER DATABASE [student club] SET  MULTI_USER 
GO
ALTER DATABASE [student club] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [student club] SET DB_CHAINING OFF 
GO
ALTER DATABASE [student club] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [student club] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [student club] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [student club] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'student club', N'ON'
GO
ALTER DATABASE [student club] SET QUERY_STORE = ON
GO
ALTER DATABASE [student club] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [student club]
GO
/****** Object:  Table [dbo].[Admin]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Admin](
	[AdminID] [int] NOT NULL,
	[Username] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
	[email] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[AdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Club_Leaders]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Club_Leaders](
	[LeadershipID] [int] NOT NULL,
	[StudentID] [int] NULL,
	[ClubID] [int] NULL,
	[LeadershipPosition] [varchar](100) NULL,
PRIMARY KEY CLUSTERED 
(
	[LeadershipID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Club_Members]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Club_Members](
	[MembershipID] [int] NOT NULL,
	[StudentID] [int] NULL,
	[ClubID] [int] NULL,
	[JoinDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[MembershipID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Clubs]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Clubs](
	[ClubID] [int] NOT NULL,
	[ClubName] [varchar](100) NULL,
	[Description] [text] NULL,
PRIMARY KEY CLUSTERED 
(
	[ClubID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Event_Admin]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Event_Admin](
	[EventAdminID] [int] NOT NULL,
	[EventID] [int] NULL,
	[AdminID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EventAdminID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Event_participants]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Event_participants](
	[EventParticipantID] [int] NOT NULL,
	[EventID] [int] NULL,
	[StudentID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EventParticipantID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Events]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events](
	[EventID] [int] NOT NULL,
	[EventName] [varchar](100) NULL,
	[Description] [text] NULL,
	[EventDate] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[EventID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Events_Club]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Events_Club](
	[EventClubID] [int] NOT NULL,
	[EventID] [int] NULL,
	[ClubID] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[EventClubID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Students]    Script Date: 12/6/2023 11:20:03 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Students](
	[StudentID] [int] NOT NULL,
	[Name] [varchar](50) NULL,
	[Password] [varchar](50) NULL,
	[Email] [varchar](100) NULL,
	[Batch] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[StudentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Club_Leaders]  WITH CHECK ADD FOREIGN KEY([ClubID])
REFERENCES [dbo].[Clubs] ([ClubID])
GO
ALTER TABLE [dbo].[Club_Leaders]  WITH CHECK ADD FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students] ([StudentID])
GO
ALTER TABLE [dbo].[Club_Members]  WITH CHECK ADD FOREIGN KEY([ClubID])
REFERENCES [dbo].[Clubs] ([ClubID])
GO
ALTER TABLE [dbo].[Club_Members]  WITH CHECK ADD FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students] ([StudentID])
GO
ALTER TABLE [dbo].[Event_Admin]  WITH CHECK ADD FOREIGN KEY([AdminID])
REFERENCES [dbo].[Admin] ([AdminID])
GO
ALTER TABLE [dbo].[Event_Admin]  WITH CHECK ADD FOREIGN KEY([EventID])
REFERENCES [dbo].[Events] ([EventID])
GO
ALTER TABLE [dbo].[Event_participants]  WITH CHECK ADD FOREIGN KEY([EventID])
REFERENCES [dbo].[Events] ([EventID])
GO
ALTER TABLE [dbo].[Event_participants]  WITH CHECK ADD FOREIGN KEY([StudentID])
REFERENCES [dbo].[Students] ([StudentID])
GO
ALTER TABLE [dbo].[Events_Club]  WITH CHECK ADD FOREIGN KEY([ClubID])
REFERENCES [dbo].[Clubs] ([ClubID])
GO
ALTER TABLE [dbo].[Events_Club]  WITH CHECK ADD FOREIGN KEY([EventID])
REFERENCES [dbo].[Events] ([EventID])
GO
USE [master]
GO
ALTER DATABASE [student club] SET  READ_WRITE 
GO
