# Form implementation generated from reading ui file 'c:\Users\HMB\OneDrive\Documents\GitHub\DatabseProjectStuff\DatabseProjectStuff-main\Club_Registration_4.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1102, 647)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(170, 150, 111, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 310, 111, 16))
        self.label_3.setObjectName("label_3")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(100, 270, 911, 331))
        self.groupBox.setObjectName("groupBox")
        self.CreateClubButton = QtWidgets.QPushButton(parent=self.groupBox)
        self.CreateClubButton.setGeometry(QtCore.QRect(730, 280, 93, 28))
        self.CreateClubButton.setObjectName("CreateClubButton")
        self.Clubdescription = QtWidgets.QLineEdit(parent=self.groupBox)
        self.Clubdescription.setGeometry(QtCore.QRect(20, 70, 781, 191))
        self.Clubdescription.setObjectName("Clubdescription")
        self.itemAddName = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.itemAddName.setGeometry(QtCore.QRect(260, 150, 591, 22))
        self.itemAddName.setObjectName("itemAddName")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(103, 10, 901, 87))
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName("textEdit")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(170, 230, 111, 16))
        self.label_5.setObjectName("label_5")
        self.ClubFundsLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ClubFundsLine.setGeometry(QtCore.QRect(260, 230, 591, 22))
        self.ClubFundsLine.setObjectName("ClubFundsLine")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(170, 190, 111, 16))
        self.label_2.setObjectName("label_2")
        self.ItemAddID = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ItemAddID.setGeometry(QtCore.QRect(260, 190, 591, 22))
        self.ItemAddID.setObjectName("ItemAddID")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1102, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Club Name:"))
        self.label_3.setText(_translate("MainWindow", "Club Bio/Details"))
        self.groupBox.setTitle(_translate("MainWindow", "Club Details"))
        self.CreateClubButton.setText(_translate("MainWindow", "Create"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt; font-weight:600;\">Club Creation</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "Club Funds:"))
        self.label_2.setText(_translate("MainWindow", "Club ID"))
