# Form implementation generated from reading ui file 'c:\Users\HMB\OneDrive\Documents\GitHub\DatabseProjectStuff\DatabseProjectStuff-main\Student_club_members_screen.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(986, 856)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(380, 30, 321, 87))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(266, 220, 55, 16))
        self.label.setObjectName("label")
        self.PresidentLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PresidentLine.setGeometry(QtCore.QRect(326, 220, 441, 22))
        self.PresidentLine.setObjectName("PresidentLine")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 270, 91, 21))
        self.label_2.setObjectName("label_2")
        self.VicePresidentLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.VicePresidentLine.setGeometry(QtCore.QRect(326, 270, 441, 22))
        self.VicePresidentLine.setObjectName("VicePresidentLine")
        self.SecretaryLine = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.SecretaryLine.setGeometry(QtCore.QRect(326, 320, 441, 22))
        self.SecretaryLine.setObjectName("SecretaryLine")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 320, 61, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(490, 410, 101, 20))
        self.label_4.setObjectName("label_4")
        self.BackButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.BackButton.setGeometry(QtCore.QRect(490, 670, 93, 28))
        self.BackButton.setObjectName("BackButton")
        self.MembersTable = QtWidgets.QTableView(parent=self.centralwidget)
        self.MembersTable.setGeometry(QtCore.QRect(335, 440, 421, 192))
        self.MembersTable.setObjectName("MembersTable")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 986, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">CLUB MEMBERS</span></p></body></html>"))
        self.label.setText(_translate("MainWindow", "President:"))
        self.label_2.setText(_translate("MainWindow", "Vice President:"))
        self.label_3.setText(_translate("MainWindow", "Secretary"))
        self.label_4.setText(_translate("MainWindow", "Member List"))
        self.BackButton.setText(_translate("MainWindow", "Back"))
